server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location = /bookroom_source.zip {
        add_header Content-Type application/zip;
        add_header Content-Disposition 'attachment; filename="bookroom_source.zip"';
        try_files /bookroom_source.zip =404;
    }
}
